### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by dubeschr** [hnolCol/instantclue#12]
Hello,
First of all thank you for developing Instant Clue, it's really a great tool.
When I use a scatter plot with my data, I get the following message: "Session not saved. error can't pickle _tkinter.tkapp object" (screenshot below). However, when I use a box plot, it is possible to save the session.
I tried to open Instant Clue in administrator mode and also to move the whole folder to another disk but it is still not possible to save the session.
Do you have a solution? Maybe with the next version?
Thanks 
Christophe

![image](https://user-images.githubusercontent.com/49344898/97296917-9bc92380-1851-11eb-95a6-5446a24a07b3.png)

**Comment by bbany** [comment]
Same issue.............looking forward to the next version

**Comment by hnolCol** [comment]
Instant Clue got a new user interface and new features. We have moved to a new framework, hence the long time since the last release. Please download the new version from [here](https://github.com/hnolCol/instantclue/releases) The Session Saving is still limited (current graph is not saved), but will receive updates in the very near future. 

I am closing this issue, if you still get errors I will reopen or you can create a new issue. For future requests, please use the [discussion forum](https://github.com/hnolCol/instantclue/discussions) on Github. 

Best wishes

Hendrik
